import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { Hind_Siliguri, Sora } from 'next/font/google'
import './globals.css'

const sora = Sora({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin-ext'],
})

const hindSiliguri = Hind_Siliguri({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin-ext'],
})

export const metadata = {
  title: 'LWS',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children, params: { lang } }) {
  return (
    <html lang={lang}>
      <body
        className={
          sora.className +
          ' dark:bg-body bg-white dark:text-white text-dark  ' +
          hindSiliguri.className
        }
      >
        <Header />
        <main>{children}</main>
        <Footer />
        <div id="model_div"/>
      </body>
    </html>
  )
}
